// Language translations for English and Nepali
export type Language = 'en' | 'ne';

export const translations = {
  en: {
    slogan: "Choose your style",
    address: "Mainroad, Bardibas-1, Mahottari, Nepal",
    searchPlaceholder: "Search for clothes, shoes & more...",
    clear: "Clear",
    myAccount: "My Account",
    manageSignOut: "Manage / Sign Out",
    signInRegister: "Sign in / Register",
    wishlist: "Wishlist",
    cart: "Cart",
    backToStore: "Back to Store",
    closePanel: "Close Panel",
    adminControl: "Admin Panel Control",
    currentlyEditing: "Currently Editing",
    home: "HOME",
    men: "MEN",
    women: "WOMEN",
    kids: "KIDS",
    shoes: "SHOES",
    accessories: "ACCESSORIES",
    brands: "BRANDS",
    newArrivals: "NEW ARRIVALS",
    offers: "OFFERS",
    contactUs: "CONTACT US",
    loginAdmin: "LOGIN / ADMIN",
    orderTracking: "ORDER TRACKING",
    feedback: "FEEDBACK",
    trackingTitle: "Order Tracking Portal",
    enterOrderId: "Enter Your Order ID",
    trackButton: "TRACK PARCEL",
    orderIdPlaceholder: "E.g., LUCKY-123456-NP",
    statusPlaced: "Order Placed",
    statusProcessing: "Processing",
    statusDispatched: "In Transit",
    statusOutForDelivery: "Out for Delivery",
    statusDelivered: "Delivered",
    mapView: "Live Delivery Route Map (Mahottari, Nepal)",
    destination: "Destination",
    courierName: "Courier Partner",
    estimatedArrival: "Estimated Arrival",
    feedbackTitle: "Customer Reviews & Feedback",
    overallRating: "Overall Store Rating",
    submitFeedback: "Submit Feedback",
    writeReview: "Write Your Review",
    yourName: "Your Full Name",
    rating: "Rating",
    categoryPurchased: "Category Purchased",
    yourReview: "Your Review Comments",
    postReview: "POST REVIEW",
    rgbMode: "RGB Mode",
    rgbOn: "RGB ON 🌈",
    rgbOff: "RGB OFF ⚪",
    listening: "Listening...",
    speakNow: "Speak now to search clothes & footwear",
    speechError: "Speech recognition not supported or permission denied.",
    nepaliLabel: "नेपाली",
    englishLabel: "English",
    addedToWishlist: "Added to Wishlist! ❤️",
    removedFromWishlist: "Removed from Wishlist! 💔",
    orderFound: "Order Details Found",
    timeline: "Delivery Timeline",
    noOrderFound: "Enter a valid order ID to track"
  },
  ne: {
    slogan: "आफ्नो शैली रोज्नुहोस्",
    address: "मुख्य सडक, बर्दिबास-१, महोत्तरी, नेपाल",
    searchPlaceholder: "कपडा, जुत्ता र थप कुराहरू खोज्नुहोस्...",
    clear: "हटाउनुहोस्",
    myAccount: "मेरो खाता",
    manageSignOut: "साइन आउट / व्यवस्थापन",
    signInRegister: "साइन इन / दर्ता",
    wishlist: "इच्छासूची",
    cart: "झोला / कार्ट",
    backToStore: "स्टोरमा फिर्ता",
    closePanel: "प्यानल बन्द गर्नुहोस्",
    adminControl: "एडमिन प्यानल नियन्त्रण",
    currentlyEditing: "हाल सम्पादन भइरहेको",
    home: "गृहपृष्ठ",
    men: "पुरुष",
    women: "महिला",
    kids: "बालबालिका",
    shoes: "जुत्ता",
    accessories: "एसेसरिज",
    brands: "ब्रान्डहरू",
    newArrivals: "नयाँ आगमन",
    offers: "अफरहरू",
    contactUs: "सम्पर्क",
    loginAdmin: "लगइन / एडमिन",
    orderTracking: "अर्डर ट्र्याकिङ",
    feedback: "सुझाव र प्रतिक्रिया",
    trackingTitle: "अर्डर ट्र्याकिङ पोर्टल",
    enterOrderId: "आफ्नो अर्डर ID राख्नुहोस्",
    trackButton: "ट्र्याक गर्नुहोस्",
    orderIdPlaceholder: "उदाहरण: LUCKY-123456-NP",
    statusPlaced: "अर्डर प्राप्त भयो",
    statusProcessing: "प्रशोधन हुँदैछ",
    statusDispatched: "मार्गमा छ",
    statusOutForDelivery: "वितरणको लागि निस्कियो",
    statusDelivered: "वितरण गरियो",
    mapView: "प्रत्यक्ष डेलिभरी मार्ग नक्सा (महोत्तरी, नेपाल)",
    destination: "गन्तव्य",
    courierName: "डेलिभरी साझेदार",
    estimatedArrival: "अनुमानित आगमन",
    feedbackTitle: "ग्राहक समीक्षा र प्रतिक्रिया",
    overallRating: "समग्र स्टोर मूल्याङ्कन",
    submitFeedback: "प्रतिक्रिया दिनुहोस्",
    writeReview: "आफ्नो समीक्षा लेख्नुहोस्",
    yourName: "तपाईंको पूरा नाम",
    rating: "मूल्याङ्कन",
    categoryPurchased: "खरिद गरिएको विधा",
    yourReview: "तपाईंको समीक्षा प्रतिक्रिया",
    postReview: "समीक्षा पोष्ट गर्नुहोस्",
    rgbMode: "आरजीबी मोड",
    rgbOn: "आरजीबी अन 🌈",
    rgbOff: "आरजीबी अफ ⚪",
    listening: "सुन्दैछ...",
    speakNow: "खोज्नको लागि बोल्नुहोस्",
    speechError: "वाणी पहिचान समर्थित छैन वा अनुमति अस्वीकृत भयो।",
    nepaliLabel: "नेपाली",
    englishLabel: "English",
    addedToWishlist: "इच्छासूचीमा थपियो! ❤️",
    removedFromWishlist: "इच्छासूचीबाट हटाइयो! 💔",
    orderFound: "अर्डर विवरण फेला पर्यो",
    timeline: "डेलिभरी समयरेखा",
    noOrderFound: "ट्र्याक गर्न वैध अर्डर ID प्रविष्ट गर्नुहोस्"
  }
};
